version: "3"

services:
  keycloak:
    command: start-dev
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${DB_DEFAULT}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    image: ${KEYCLOAK_CONTAINER_IMAGE}
    ports:
      - ${KEYCLOAK_HOST_PORT}:${KEYCLOAK_CONTAINER_PORT}
    volumes:
      - keycloak_data:/data
      - ./keycloak/providers:/opt/jboss/keycloak/providers
      - ./keycloak/standalone/configuration:/opt/jboss/keycloak/standalone/configuration
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: ${KEYCLOAK_IPV4}

  postgres:
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_DEFAULT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: "exit 0"
    image: ${DB_CONTAINER_IMAGE}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data 
    networks:
      network_sso:
        ipv4_address: ${DB_IPV4}

networks:
  network_sso:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IPV4}

volumes:
  keycloak_data:
  postgresql:
  postgresql_data:


