version: "3.8"
services:
  postgres:
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: ${DB_CONTAINER_IMAGE}
    restart: always
    volumes:
       - postgres-db:/data/postgres
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}

volumes:
  postgres-db: