version: "3.8"
services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: ${POSTGRES_CONTAINER_IMAGE}
    restart: always
    volumes:
       - postgres-db:/data/postgres
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}

volumes:
  postgres-db: